### ISSUE TITLE
Travis failures

### ISSUE THREAD

**Issue by simonedeponti** [ploneintranet/ploneintranet.workspace#38]
Travis builds are currently failing for unknown reasons (the tests run perfectly locally, and the same holds for jenkins).

Right now it's also very hard to debug why this is happening, although I noticed that maybe there are files that robot generates that might be of interest to us:

    Output:  /home/travis/build/ploneintranet/ploneintranet.workspace/parts/test/workspace/Site_Administrator_can_add_example_user_as_member_of_workspace/output.xml
    Log:     /home/travis/build/ploneintranet/ploneintranet.workspace/parts/test/workspace/Site_Administrator_can_add_example_user_as_member_of_workspace/log.html
    Report:  /home/travis/build/ploneintranet/ploneintranet.workspace/parts/test/workspace/Site_Administrator_can_add_example_user_as_member_of_workspace/report.html

These files are not accessible from Travis, however in this stackoverflow (http://stackoverflow.com/a/21781195/967274) they suggest you can, after failure, zip & send them somewhere (via mail or scp or whatelse).

If we are interested in fixing travis, it might be worth a shot to try to retrieve those files and see what went wrong.

**Comment by wengole** [comment]
We're not using travis anymore
